services:
    sudoku.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - SudokuBundle\Entity\SudokuGame

    sudoku.validator:
            class: SudokuBundle\Library\Validator\UniqueValidator

    sudoku.board:
        class: SudokuBundle\Library\Board
        arguments:
            - '\SudokuBundle\Library\Value\NumberValue'
            - 9
            - "@sudoku.validator"

    sudoku.root:
        class: SudokuBundle\Root\Game
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@sudoku.repository"
            - "@sudoku.board"