services:
#    sudoku.example:
#        class: SudokuBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    sudoku.board:
    class: SudokuBundle\Library\Board
    arguments: ["@request_stack","@doctrine.orm.entity_manager"]
    scope: request
