<?php

namespace SudokuBundle\Repository;

/**
 * SudokuGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SudokuGameRepository extends \Doctrine\ORM\EntityRepository
{
}
